export const NEGATIVE_CORE=["no morphing","no teleportation","no portal","no fantasy glow","no identity blending","no extra people","no body fusion","no bad anatomy","no extra limbs","no broken hands","no camera orbit","no lens redesign","no aggressive zoom","no sepia filter","no memory FX"].join(", ");
export const SCHOOL_ANALYSIS_PROMPT=`Analyze SCHOOL_IDENTITY as the strict child identity, embedded location and era-memory source. Return STRICT JSON only. Separate visible evidence from inferred and unknown details. Describe child identity, apparent age, face, hair, wardrobe, era, room geometry, furniture, materials, light direction, camera/crop and must-preserve memory anchors. Never invent a generic classroom.`;
export const ADULT_ANALYSIS_PROMPT=`Analyze ADULT_IDENTITY as the strict present-day identity source. Return STRICT JSON only describing apparent age, facial geometry, hair, distinctive traits, body proportions, wardrobe and source limitations. Do not beautify or reinterpret.`;
export function memorySpacePlanPrompt(s:unknown,a:unknown){return`Create STRICT JSON MEMORY_SPACE_PLAN. Preserve recognizable environment DNA and era from SCHOOL_IDENTITY, logically extend only missing space, keep child readable center-left and reserve screen-right for adult entrance. SCHOOL=${JSON.stringify(s)} ADULT=${JSON.stringify(a)}`}
export function masterFramePrompt(p:unknown,s:unknown){return`Use SCHOOL_IDENTITY simultaneously as strict child identity reference, embedded-location reference and era-memory source. Create MASTER_FIRST_FRAME, vertical 9:16, photorealistic. Preserve child identity, age, visible wardrobe logic, era, light and recognizable location DNA. Reconstruct only plausible missing areas. Child center-left with enough body visible for later hug; leave screen-right free. NO ADULT. No generic luxury classroom, modernization, sepia, glow or fantasy. ${NEGATIVE_CORE}. PLAN=${JSON.stringify(p)} SCHOOL=${JSON.stringify(s)}`}
export function meetingFramePrompt(passport:unknown,adult:unknown){return`MASTER_FIRST_FRAME is immutable. Insert ADULT_IDENTITY on screen-right a few steps away BEFORE contact. SCHOOL_IDENTITY only locks the child. Do not change child, camera, crop, perspective, room geometry, furniture or lighting. Preserve adult identity strictly, correct scale, feet, shadows and light. Same real person at two ages, two separate bodies. ${NEGATIVE_CORE}. FRAME_PASSPORT=${JSON.stringify(passport)} ADULT=${JSON.stringify(adult)}`}
export function videoPrompt(passport:unknown){return`Single continuous photorealistic 15-second vertical 9:16 shot. MASTER_FIRST_FRAME is exact opening/environment/camera anchor. MEETING_REFERENCE_FRAME + SCHOOL_IDENTITY + ADULT_IDENTITY are visual/identity references. 0-3 child alone; 3-5.5 adult enters physically from screen-right; 5.5-7.5 restrained recognition; 7.5-11.5 gradual anatomically correct hug; 11.5-15 stable emotional hold, final ~2 seconds nearly still. Hug: approach→slow→lower slightly→open arms→child step→shoulder/upper-torso contact→child wraps arms→adult completes embrace→stable hold. Preserve both identities, ages, environment, camera, era and lighting. ${NEGATIVE_CORE}. FRAME_PASSPORT=${JSON.stringify(passport)}`}
export const FRAME_PASSPORT_PROMPT=`Return STRICT JSON immutable frame contract: camera_position,camera_height,yaw,pitch,roll,focal_description,horizon,crop,geometry,furniture_relationships,light_direction. Use unknown where not inferable.`;
export const MASTER_QC_PROMPT=`Return STRICT JSON {"scores":{"child_identity":0..1,"memory_continuity":0..1,"environment_reconstruction":0..1,"era_authenticity":0..1,"composition":0..1},"notes":""}. Identity and memory continuity outrank beauty.`;
export const MEETING_QC_PROMPT=`Return STRICT JSON {"scores":{"adult_identity":0..1,"child_preservation":0..1,"environment_consistency":0..1,"scale":0..1},"notes":""}.`;
export const VIDEO_QC_PROMPT=`Return STRICT JSON {"scores":{"child_identity":0..1,"adult_identity":0..1,"environment_camera_consistency":0..1,"temporal_continuity":0..1,"hug_anatomy":0..1,"final_frame_quality":0..1},"notes":""}.`;
