from pathlib import Path
from PIL import Image, ImageDraw, ImageFont, ImageOps
from .storage import project_dir


def _fonts():
    try:
        return (
            ImageFont.truetype("DejaVuSans-Bold.ttf", 46),
            ImageFont.truetype("DejaVuSans.ttf", 28),
            ImageFont.truetype("DejaVuSans-Bold.ttf", 34),
        )
    except Exception:
        fallback = ImageFont.load_default()
        return fallback, fallback, fallback


def render_card(project_id: str, decade: str, state: dict, source_image: str | Path) -> str:
    """Render a deterministic 16:9 card. Typography is never generated by AI."""
    pdir = project_dir(project_id)
    output = pdir / "cards" / f"{project_id}_{decade}_card.png"

    source = Image.open(source_image).convert("RGB")
    canvas = ImageOps.fit(source, (1920, 1080), method=Image.Resampling.LANCZOS, centering=(0.5, 0.5))
    draw = ImageDraw.Draw(canvas, "RGBA")

    # Fixed MARINS top overlay. This is intentionally deterministic across the series.
    draw.rectangle((0, 0, 1920, 150), fill=(0, 48, 80, 238))
    surname_font, meta_font, decade_font = _fonts()

    person = state["person"]
    surname = person["surname"].upper()
    name = person.get("name", "")
    position = person["position"]
    school_years = person["school_years"]

    draw.text((64, 28), f"{surname} {name}".strip(), font=surname_font, fill=(255, 255, 255, 255))
    draw.text((64, 88), position, font=meta_font, fill=(222, 234, 242, 255))

    decade_box = draw.textbbox((0, 0), decade, font=decade_font)
    decade_w = decade_box[2] - decade_box[0]
    draw.text((1856 - decade_w, 34), decade, font=decade_font, fill=(255, 255, 255, 255))
    years_box = draw.textbbox((0, 0), school_years, font=meta_font)
    years_w = years_box[2] - years_box[0]
    draw.text((1856 - years_w, 92), school_years, font=meta_font, fill=(222, 234, 242, 255))

    canvas.save(output, quality=95)
    return str(output)


def render_card_mock(project_id: str, decade: str, state: dict) -> str:
    """Compatibility fallback used before a provider image exists."""
    pdir = project_dir(project_id)
    placeholder = pdir / "preview" / f"{project_id}_{decade}_placeholder.png"
    Image.new("RGB", (1920, 1080), (20, 28, 42)).save(placeholder)
    return render_card(project_id, decade, state, placeholder)
